server:
  port: ${port:8888}

spring:
  application:
    name: config-server

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Desktop/MyRentalPlatform/git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, beans, httptrace, busrefresh